/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TrustChainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "accessList"
      | "activateEmergency"
      | "canAccess"
      | "emergencyMode"
      | "fileCount"
      | "files"
      | "grantAccess"
      | "trustScore"
      | "uploadFile"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccessGranted"
      | "EmergencyActivated"
      | "FileUploaded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "accessList",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "activateEmergency",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "canAccess",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyMode",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "fileCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "files", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "grantAccess",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "trustScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "uploadFile",
    values: [BytesLike, string]
  ): string;

  decodeFunctionResult(functionFragment: "accessList", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "activateEmergency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canAccess", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fileCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "files", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "grantAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "trustScore", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "uploadFile", data: BytesLike): Result;
}

export namespace AccessGrantedEvent {
  export type InputTuple = [
    fileId: BigNumberish,
    user: AddressLike,
    expiry: BigNumberish
  ];
  export type OutputTuple = [fileId: bigint, user: string, expiry: bigint];
  export interface OutputObject {
    fileId: bigint;
    user: string;
    expiry: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyActivatedEvent {
  export type InputTuple = [admin: AddressLike];
  export type OutputTuple = [admin: string];
  export interface OutputObject {
    admin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FileUploadedEvent {
  export type InputTuple = [fileId: BigNumberish, owner: AddressLike];
  export type OutputTuple = [fileId: bigint, owner: string];
  export interface OutputObject {
    fileId: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TrustChain extends BaseContract {
  connect(runner?: ContractRunner | null): TrustChain;
  waitForDeployment(): Promise<this>;

  interface: TrustChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  accessList: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [[bigint, boolean] & { expiry: bigint; allowed: boolean }],
    "view"
  >;

  activateEmergency: TypedContractMethod<[], [void], "nonpayable">;

  canAccess: TypedContractMethod<
    [_fileId: BigNumberish, _user: AddressLike],
    [boolean],
    "view"
  >;

  emergencyMode: TypedContractMethod<[], [boolean], "view">;

  fileCount: TypedContractMethod<[], [bigint], "view">;

  files: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, boolean] & {
        fileHash: string;
        ipfsHash: string;
        owner: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  grantAccess: TypedContractMethod<
    [_fileId: BigNumberish, _user: AddressLike, _expiry: BigNumberish],
    [void],
    "nonpayable"
  >;

  trustScore: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  uploadFile: TypedContractMethod<
    [_fileHash: BytesLike, _ipfsHash: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "accessList"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [[bigint, boolean] & { expiry: bigint; allowed: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "activateEmergency"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "canAccess"
  ): TypedContractMethod<
    [_fileId: BigNumberish, _user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "emergencyMode"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "fileCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "files"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, boolean] & {
        fileHash: string;
        ipfsHash: string;
        owner: string;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantAccess"
  ): TypedContractMethod<
    [_fileId: BigNumberish, _user: AddressLike, _expiry: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "trustScore"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "uploadFile"
  ): TypedContractMethod<
    [_fileHash: BytesLike, _ipfsHash: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AccessGranted"
  ): TypedContractEvent<
    AccessGrantedEvent.InputTuple,
    AccessGrantedEvent.OutputTuple,
    AccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyActivated"
  ): TypedContractEvent<
    EmergencyActivatedEvent.InputTuple,
    EmergencyActivatedEvent.OutputTuple,
    EmergencyActivatedEvent.OutputObject
  >;
  getEvent(
    key: "FileUploaded"
  ): TypedContractEvent<
    FileUploadedEvent.InputTuple,
    FileUploadedEvent.OutputTuple,
    FileUploadedEvent.OutputObject
  >;

  filters: {
    "AccessGranted(uint256,address,uint256)": TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;
    AccessGranted: TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;

    "EmergencyActivated(address)": TypedContractEvent<
      EmergencyActivatedEvent.InputTuple,
      EmergencyActivatedEvent.OutputTuple,
      EmergencyActivatedEvent.OutputObject
    >;
    EmergencyActivated: TypedContractEvent<
      EmergencyActivatedEvent.InputTuple,
      EmergencyActivatedEvent.OutputTuple,
      EmergencyActivatedEvent.OutputObject
    >;

    "FileUploaded(uint256,address)": TypedContractEvent<
      FileUploadedEvent.InputTuple,
      FileUploadedEvent.OutputTuple,
      FileUploadedEvent.OutputObject
    >;
    FileUploaded: TypedContractEvent<
      FileUploadedEvent.InputTuple,
      FileUploadedEvent.OutputTuple,
      FileUploadedEvent.OutputObject
    >;
  };
}
